# Generated by Django 3.2.18 on 2023-05-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230502_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='post_<django.db.models.query_utils.DeferredAttribute object at 0x000001CFCB69B090>_<property object at 0x000001CFCB6B0130>', max_length=250, unique_for_date='published_date'),
        ),
    ]
